version: "3.8"

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: always
    ports:
      - "11435:11434"
    volumes:
      - ollama_models:/root/.ollama
    command: ["serve"]
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]  # Habilitar GPU para este servicio

  openwebui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: openwebui
    restart: always
    depends_on:
      - ollama
    ports:
      - "3000:3000"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]  # Habilitar GPU para este servicio

  fastapi:
    build: ./api
    container_name: fastapi
    restart: always
    depends_on:
      - ollama
    ports:
      - "8001:8000"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

volumes:
  ollama_models: